global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
    scrape_timeout: 15s

    target_groups:
      - targets: ['192.168.178.44:9090']
      - targets: ['192.168.178.44:9100']

    metric_relabel_configs:
      - source_labels: [id]
        action: replace
        regex: ^\/machine.slice\/systemd-nspawn\@(.+)\.service 
        target_label: container_name
        replacement: $1

